name: bayes
dependencies:
  - python==3.6.0
  - jupyter
  - scipy==1.1.0
  - pandas==0.23.4
  - matplotlib
  - seaborn==0.9.0
  - pip:
    - pymc==2.3.4
    - pyzmq>=13.1.0
    - tornado>=3.0.2
    #- wsgiref>=0.1.2 #; python_version < '3.0'
    - praw>=2.0.0
    - jinja2
